### ISSUE TITLE
 Move/Walk

### ISSUE THREAD

**Issue by frozensquid** [romansvozil/nostale_utils#5]
Hello,
It seams that it's not possible to move/walk with packets sent in packetlogger.

Is it possible ? If yes, how ?

Thank you
Best regards,

**Comment by romansvozil** [comment]
The easy way is sending walk packet (obviously you have to respect all the rules of the packet, like how far you can go with each walk packet, how long to wait before sending another, stuns etc.) and right after receiving tp packet, which "synchronises" your client-side state with server.

Sorry for late response.
